---
- hosts: all

  roles:
    - { role: "azavea.postgresql" }
    - { role: "azavea.postgis" }
    - { role: "azavea.postgresql-support" }
    - { role: "azavea.nginx", nginx_delete_default_site: True }

  tasks:

    - include_vars: secrets.yml

    - name: Create postgres database
      postgresql_db: name={{ postgres_db }}
      sudo_user: postgres

    - name: Create postgres user
      postgresql_user: db={{ postgres_db }}
                       name={{ postgres_user }}
                       password={{ postgres_password }}
                       role_attr_flags=SUPERUSER
      sudo_user: postgres

    - name: Add PostGIS extension
      sudo_user: postgres
      command: psql {{ postgres_db }} -c "CREATE EXTENSION postgis"
      register: psql_result
      failed_when: >
        psql_result.rc != 0 and ("already exists" not in psql_result.stderr)
      changed_when: "psql_result.rc == 0"

    - name: Configure Nginx site
      template: src=templates/nginx-votewatch.conf.j2
                dest=/etc/nginx/sites-available/votewatch-app.conf
      notify:
        - Restart Nginx

    - name: Enable Nginx site
      file: src=/etc/nginx/sites-available/votewatch-app.conf
            dest=/etc/nginx/sites-enabled/votewatch-app.conf
            state=link
      notify:
        - Restart Nginx
